-- 🛡️ SCRIPT DE BASE DE DATOS: SERENAZGO SURQUILLO
-- Puedes copiar y pegar todo este código en el "SQL Editor" de tu proyecto de Supabase.

-- 1. Tabla de Perfiles (Serenos, Conductores, Supervisores)
CREATE TABLE public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  dni text unique not null,
  full_name text not null,
  role text check (role in ('SERENO', 'CONDUCTOR', 'SUPERVISOR')) not null,
  sector text default 'Sector 03',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar la seguridad RLS (Row Level Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad de Perfiles
CREATE POLICY "Los perfiles son visibles para todo el equipo" 
ON public.profiles FOR SELECT USING (true);

CREATE POLICY "Los usuarios solo pueden editar su propio perfil" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);


-- 2. Tabla del Muro Comunitario (Publicaciones y Alertas SOS)
CREATE TABLE public.muro_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  content text not null,
  image_url text,
  is_sos boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar seguridad en el Muro
ALTER TABLE public.muro_posts ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad del Muro
CREATE POLICY "Todos los serenos autenticados pueden leer el muro"
ON public.muro_posts FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Los serenos solo pueden publicar a su nombre"
ON public.muro_posts FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 3. Crear Storage para las Fotos de las Ocurrencias
insert into storage.buckets (id, name, public) values ('ocurrencias', 'ocurrencias', true);

CREATE POLICY "Cualquiera puede ver las fotos"
ON storage.objects FOR SELECT USING (bucket_id = 'ocurrencias');

CREATE POLICY "Solo autenticados pueden subir fotos"
ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'ocurrencias' AND auth.role() = 'authenticated');
